FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    unzip \
    ca-certificates \
    libx11-dev \
    libx11-xcb-dev \
    libgl1-mesa-glx \
    libxss1 \
    libgdk-pixbuf2.0-0 \
    libnss3 \
    libgbm-dev \
    libasound2

RUN curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb && \
    dpkg -i google-chrome.deb && \
    apt-get -f install -y && \
    rm google-chrome.deb

RUN pip install chromedriver-binary-auto

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . /app

WORKDIR /app

CMD ["python", "app.py"]
